# Generated by Django 5.0.6 on 2024-05-19 16:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("video_app", "0002_webpage_video_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="drive_id",
        ),
        migrations.RemoveField(
            model_name="video",
            name="resolutions",
        ),
    ]
